server:
  port: 8080
spring:
  redis:
    host: 192.168.134.111
    port: 6379
  application:
    name: service-verification-code
eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://eureka1.com:7901/eureka
